project:
  type: book
  output-dir: docs

engines: ["julia"]

execute:
  freeze: auto

book:
  title: "Geoscientific Machine Learning"
  author: "Pankaj K Mishra"
  site-url: "https://pankajkmishra.github.io/geo-sciml/"
  output-file: "geo-sciml"
  downloads: [pdf]
  search: true
  page-footer:
    center: '<span style="white-space:nowrap;">✍️ Pankaj K Mishra <a href="https://www.linkedin.com/in/pankajkmishra01/" target="_blank" style="margin-left:0.3em;text-decoration:none;"><i class="bi bi-linkedin" style="font-size:1.2em;vertical-align:middle;"></i></a></span>'
  sidebar:
    style: docked
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/pankajkmishra/geo-sciml
  page-navigation: true
  chapters:
    - text: "About this book"
      file: index.md
    - chapters/01-getting-started-julia.qmd
    - chapters/02-files-data.qmd
    - chapters/03-plotting-maps.qmd
    - chapters/04-neural-networks.qmd
    - chapters/05-inverse-modeling.qmd
    - chapters/06-ai-surrogates.qmd
    - chapters/07-applications.qmd

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true
    toc-title: "Contents"
    toc-depth: 3
    toc-location: right
    number-sections: true
    code-link: true
    code-copy: true
    code-overflow: wrap
    grid:
      sidebar-width: 450px
      body-width: 900px
      margin-width: 200px
      gutter-width: 1.5em
  pdf:
    number-sections: true
    number-depth: 3
    toc: true
    toc-depth: 3
    toc-title: "Table of Contents"
    colorlinks: true
    linkcolor: blue
    toccolor: blue
    urlcolor: blue
    citecolor: blue
    mainfont: "Libertinus Serif"
    sansfont: "Libertinus Sans"
    monofont: "JuliaMono"
    mathfont: "Libertinus Math"
    include-in-header:
      text: |
        \setcounter{secnumdepth}{3}
