using Dates

const ROOT_DIR = normpath(joinpath(@__DIR__, ".."))
const CHAPTERS_DIR = joinpath(ROOT_DIR, "chapters")
const OUTPUT_DIR = @__DIR__

function is_julia_fence(line::AbstractString)
    # Accept both Quarto-style Julia fences and plain markdown Julia fences.
    stripped = strip(line)
    return occursin(r"^```\{julia.*\}$", stripped) || stripped == "```julia"
end

function chapter_script_path(chapter_path::AbstractString)
    filename = replace(basename(chapter_path), r"\.qmd$" => ".jl")
    return joinpath(OUTPUT_DIR, filename)
end

function collect_julia_chunks(chapter_path::AbstractString)
    lines = readlines(chapter_path)
    chunks = String[]
    in_chunk = false
    chunk_lines = String[]

    for line in lines
        stripped = strip(line)

        if !in_chunk && is_julia_fence(line)
            in_chunk = true
            empty!(chunk_lines)
            continue
        end

        if in_chunk && stripped == "```"
            push!(chunks, join(chunk_lines, "\n"))
            in_chunk = false
            empty!(chunk_lines)
            continue
        end

        if in_chunk
            # Quarto chunk options belong to the manuscript, not the exported script.
            startswith(stripped, "#|") && continue
            push!(chunk_lines, line)
        end
    end

    return chunks
end

function render_script(chapter_path::AbstractString, chunks::Vector{String})
    relative_source = relpath(chapter_path, ROOT_DIR)
    generated_at = Dates.format(now(), dateformat"yyyy-mm-dd HH:MM:SS")
    buffer = IOBuffer()

    println(buffer, "# Generated from $(relative_source)")
    println(buffer, "# Generated by scripts/00-extract_chapter_code.jl on $(generated_at)")
    println(buffer, "# Regenerate with: julia scripts/00-extract_chapter_code.jl")
    println(buffer)

    if isempty(chunks)
        println(buffer, "# No Julia code blocks were found in this chapter.")
        return String(take!(buffer))
    end

    for (index, chunk) in enumerate(chunks)
        # Preserve chunk boundaries so exported scripts are easy to trace back to the chapter.
        println(buffer, "#-----chunk $(index)------")
        println(buffer, "# Source: $(relative_source)")
        println(buffer)
        println(buffer, rstrip(chunk))
        if index != length(chunks)
            println(buffer)
            println(buffer)
        end
    end

    return String(take!(buffer))
end

function main()
    # Export one script per chapter, mirroring the manuscript filenames.
    chapter_paths = sort(filter(path -> endswith(path, ".qmd"), readdir(CHAPTERS_DIR; join = true)))

    for chapter_path in chapter_paths
        chunks = collect_julia_chunks(chapter_path)
        script_path = chapter_script_path(chapter_path)
        write(script_path, render_script(chapter_path, chunks))
        println("Wrote $(relpath(script_path, ROOT_DIR))")
    end
end

main()