# Generated from chapters/01-getting-started-julia.qmd
# Generated by scripts/extract_chapter_code.jl on 2026-04-04 00:23:54
# Regenerate with: julia scripts/extract_chapter_code.jl

#-----chunk 1------
# Source: chapters/01-getting-started-julia.qmd

println("I am Julia code")


#-----chunk 2------
# Source: chapters/01-getting-started-julia.qmd

println("Hello, Julia!")
x = [1, 2, 3, 4, 5]
println("Sum: ", sum(x))


#-----chunk 3------
# Source: chapters/01-getting-started-julia.qmd

1 + 2, sin(1.0)


#-----chunk 4------
# Source: chapters/01-getting-started-julia.qmd

a = 10
b = 3
a + b, a - b, a * b, a / b


#-----chunk 5------
# Source: chapters/01-getting-started-julia.qmd

x = [1, 2, 3, 4, 5]
sum(x), length(x)


#-----chunk 6------
# Source: chapters/01-getting-started-julia.qmd

name = "Julia"
println("Hello, $name!")


#-----chunk 7------
# Source: chapters/01-getting-started-julia.qmd

f(x) = x^2 + 2x + 1
f(3)


#-----chunk 8------
# Source: chapters/01-getting-started-julia.qmd

function kinetic_energy(mass, velocity)
    return 0.5 * mass * velocity^2
end

kinetic_energy(70.0, 3.0)   # a 70 kg person walking at 3 m/s


#-----chunk 9------
# Source: chapters/01-getting-started-julia.qmd

function minmax(x)
    return minimum(x), maximum(x)
end

lo, hi = minmax([4, 1, 7, 2])
println("min = $lo, max = $hi")


#-----chunk 10------
# Source: chapters/01-getting-started-julia.qmd

x = 5
if x > 0
    println("positive")
elseif x < 0
    println("negative")
else
    println("zero")
end


#-----chunk 11------
# Source: chapters/01-getting-started-julia.qmd

for i in 1:5
    println(i^2)
end


#-----chunk 12------
# Source: chapters/01-getting-started-julia.qmd

struct Point
    x::Float64
    y::Float64
end

p = Point(1.0, 2.0)
p.x, p.y


#-----chunk 13------
# Source: chapters/01-getting-started-julia.qmd

x = [1, 2, 3, 4]
sin.(x)              # sine of each element
x .^ 2               # square each element
x .+ 10              # add 10 to each element


#-----chunk 14------
# Source: chapters/01-getting-started-julia.qmd

f(x) = x^2 + 1
f.([1, 2, 3])        # returns [2, 5, 10]


#-----chunk 15------
# Source: chapters/01-getting-started-julia.qmd

methods(+)                # all methods for +
@which 1.0 + 2.0          # which method handles Float64 + Float64


#-----chunk 16------
# Source: chapters/01-getting-started-julia.qmd

@time sum(rand(1_000_000))     # first call: includes compilation
@time sum(rand(1_000_000))     # second call: actual speed


#-----chunk 17------
# Source: chapters/01-getting-started-julia.qmd

using BenchmarkTools
@btime sum(rand(1_000_000))


#-----chunk 18------
# Source: chapters/01-getting-started-julia.qmd

# Slow — top level
x = rand(1_000_000)
total = 0.0
for val in x
    total += val
end

# Fast — inside a function
function mysum(x)
    total = 0.0
    for val in x
        total += val
    end
    return total
end
mysum(rand(1_000_000))


#-----chunk 19------
# Source: chapters/01-getting-started-julia.qmd

A = rand(1000, 1000)

# Fast — columns in the outer loop, rows in the inner loop
for j in 1:1000       # column
    for i in 1:1000   # row
        A[i, j] += 1
    end
end


#-----chunk 20------
# Source: chapters/01-getting-started-julia.qmd

ENV["HTTP_PROXY"]       # should print your proxy address
using Pkg
Pkg.add("Example")      # should download successfully


#-----chunk 21------
# Source: chapters/01-getting-started-julia.qmd

using Pkg
Pkg.activate(".")      # use the current folder as the environment
Pkg.add("CSV")         # adds CSV to Project.toml and resolves Manifest.toml
Pkg.add("DataFrames")


#-----chunk 22------
# Source: chapters/01-getting-started-julia.qmd

using Pkg
Pkg.activate(".")       # point to the folder containing their Project.toml
Pkg.instantiate()       # download the exact versions from Manifest.toml
