# Generated from chapters/02-files-data.qmd
# Generated by scripts/extract_chapter_code.jl on 2026-04-04 00:23:54
# Regenerate with: julia scripts/extract_chapter_code.jl

#-----chunk 1------
# Source: chapters/02-files-data.qmd

# Create a small text file
open("stations.txt", "w") do f
    write(f, "Station  Latitude  Longitude  Elevation_m\n")
    write(f, "AAL      64.35     25.75      120\n")
    write(f, "BBR      61.50     23.80      95\n")
    write(f, "CCK      60.17     24.94      15\n")
end


#-----chunk 2------
# Source: chapters/02-files-data.qmd

content = read("stations.txt", String)
println(content)


#-----chunk 3------
# Source: chapters/02-files-data.qmd

open("stations.txt", "r") do f
    for line in eachline(f)
        println("→ ", line)
    end
end


#-----chunk 4------
# Source: chapters/02-files-data.qmd

open("stations.txt", "r") do f
    header = readline(f)              # read and skip the header
    for line in eachline(f)
        parts = split(line)           # splits on whitespace by default
        name  = parts[1]
        lat   = parse(Float64, parts[2])
        lon   = parse(Float64, parts[3])
        elev  = parse(Float64, parts[4])
        println("$name is at ($lat, $lon), elevation $elev m")
    end
end


#-----chunk 5------
# Source: chapters/02-files-data.qmd

# Create a space-delimited data file (no header, just numbers)
open("gravity.txt", "w") do f
    write(f, "64.35  25.75  -12.3\n")
    write(f, "64.40  25.80  -11.8\n")
    write(f, "64.45  25.85  -13.1\n")
    write(f, "64.50  25.90  -12.7\n")
    write(f, "64.55  25.95  -14.0\n")
end


#-----chunk 6------
# Source: chapters/02-files-data.qmd

using DelimitedFiles

data = readdlm("gravity.txt")       # reads into a matrix
println("Size: ", size(data))        # 5 rows, 3 columns


#-----chunk 7------
# Source: chapters/02-files-data.qmd

lat = data[:, 1]         # all rows, first column
lon = data[:, 2]         # all rows, second column
gz  = data[:, 3]         # all rows, third column

println("Latitudes: ", lat)
println("Gravity anomalies: ", gz)


#-----chunk 8------
# Source: chapters/02-files-data.qmd

# Add 1.0 to all gravity values and save
gz_corrected = gz .+ 1.0
output = hcat(lat, lon, gz_corrected)    # glue columns side by side
writedlm("gravity_corrected.txt", output, '\t')   # tab-separated

# Verify
println(read("gravity_corrected.txt", String))


#-----chunk 9------
# Source: chapters/02-files-data.qmd

using DataFrames

# Create a table of borehole samples
samples = DataFrame(
    borehole  = ["BH-01", "BH-01", "BH-01", "BH-02", "BH-02"],
    depth_m   = [10.0, 20.0, 30.0, 15.0, 25.0],
    rock_type = ["granite", "granite", "gneiss", "granite", "schist"],
    density   = [2.65, 2.68, 2.75, 2.63, 2.71]
)


#-----chunk 10------
# Source: chapters/02-files-data.qmd

using CSV

# Write to CSV
CSV.write("samples.csv", samples)

# Read it back
samples_loaded = CSV.read("samples.csv", DataFrame)


#-----chunk 11------
# Source: chapters/02-files-data.qmd

# One column - returns a vector
samples.depth_m


#-----chunk 12------
# Source: chapters/02-files-data.qmd

# Multiple columns - returns a new DataFrame
select(samples, :borehole, :density)


#-----chunk 13------
# Source: chapters/02-files-data.qmd

# Samples deeper than 20 m
filter(row -> row.depth_m > 20, samples)


#-----chunk 14------
# Source: chapters/02-files-data.qmd

# Only granite samples
filter(row -> row.rock_type == "granite", samples)


#-----chunk 15------
# Source: chapters/02-files-data.qmd

# Add a new column
samples.weight_kg = samples.density .* 1000.0   # density × 1000
samples


#-----chunk 16------
# Source: chapters/02-files-data.qmd

using Statistics

# Average density per borehole
gdf = groupby(samples, :borehole)
combine(gdf, :density => mean => :avg_density)


#-----chunk 17------
# Source: chapters/02-files-data.qmd

# Multiple summaries at once
combine(
    groupby(samples, :rock_type),
    :density => mean => :avg_density,
    :density => minimum => :min_density,
    :depth_m => maximum => :deepest
)


#-----chunk 18------
# Source: chapters/02-files-data.qmd

# A second table with borehole coordinates
locations = DataFrame(
    borehole  = ["BH-01", "BH-02", "BH-03"],
    latitude  = [64.35, 64.40, 64.45],
    longitude = [25.75, 25.80, 25.85]
)

# Inner join - only boreholes that appear in both tables
innerjoin(samples, locations, on = :borehole)


#-----chunk 19------
# Source: chapters/02-files-data.qmd

# Create data with a gap
obs = DataFrame(
    station = ["A", "B", "C", "D"],
    temp_C  = [12.3, missing, 14.1, 13.7]
)
obs


#-----chunk 20------
# Source: chapters/02-files-data.qmd

# Drop rows with missing values
dropmissing(obs, :temp_C)


#-----chunk 21------
# Source: chapters/02-files-data.qmd

# Compute mean, skipping missing values
using Statistics
mean(skipmissing(obs.temp_C))


#-----chunk 22------
# Source: chapters/02-files-data.qmd

# Build a path
path = joinpath("data", "field_campaign", "gravity.txt")
println(path)


#-----chunk 23------
# Source: chapters/02-files-data.qmd

println("Current directory: ", pwd())
println("Files here: ", readdir("."))


#-----chunk 24------
# Source: chapters/02-files-data.qmd

# Check if a file exists before reading
if isfile("samples.csv")
    println("samples.csv exists!")
else
    println("File not found")
end


#-----chunk 25------
# Source: chapters/02-files-data.qmd

# readdir returns the names of everything in a folder
for name in readdir(".")
    println(name)
end


#-----chunk 26------
# Source: chapters/02-files-data.qmd

for path in readdir("data/raw", join = true)
    println(path)
end


#-----chunk 27------
# Source: chapters/02-files-data.qmd

# Find every .csv file anywhere inside data/
for (root, dirs, files) in walkdir("data")
    for f in files
        if endswith(f, ".csv")
            full_path = joinpath(root, f)
            println(full_path)
        end
    end
end


#-----chunk 28------
# Source: chapters/02-files-data.qmd

"""
    find_files(dir, ext)

Recursively find all files with extension `ext` in `dir` and its subdirectories.
Returns a vector of full paths.
"""
function find_files(dir, ext)
    results = String[]
    for (root, dirs, files) in walkdir(dir)
        for f in files
            if endswith(f, ext)
                push!(results, joinpath(root, f))
            end
        end
    end
    return results
end


#-----chunk 29------
# Source: chapters/02-files-data.qmd

# Example: find all .dat files under a field campaign folder
dat_files = find_files("data/raw", ".dat")
println("Found $(length(dat_files)) .dat files")


#-----chunk 30------
# Source: chapters/02-files-data.qmd

example_path = joinpath("surveys", "2024", "gravity", "station_042.csv")

println("Directory:  ", dirname(example_path))
println("Filename:   ", basename(example_path))
println("Name only:  ", splitext(basename(example_path))[1])
println("Extension:  ", splitext(basename(example_path))[2])
println("Split path: ", splitpath(example_path))


#-----chunk 31------
# Source: chapters/02-files-data.qmd

# --- Set up a fake directory tree ---
for station in ["EM01", "EM02", "EM03"]
    dir = joinpath("fake_survey", station)
    mkpath(dir)    # like mkdir -p: creates all intermediate directories
    for i in 1:3
        filepath = joinpath(dir, "meas_$(lpad(i, 3, '0')).dat")
        write(filepath, "fake data for $station measurement $i\n")
    end
end
println("Created fake survey tree:")
for (root, dirs, files) in walkdir("fake_survey")
    for f in files
        println("  ", joinpath(root, f))
    end
end


#-----chunk 32------
# Source: chapters/02-files-data.qmd

# --- Find, rename, and copy ---
output_dir = "collected_data"
mkpath(output_dir)

for (root, dirs, files) in walkdir("fake_survey")
    for f in files
        if endswith(f, ".dat")
            # The station name is the immediate parent folder
            station = basename(root)

            # Build a new name: EM01_meas_001.dat
            new_name = station * "_" * f

            src = joinpath(root, f)
            dst = joinpath(output_dir, new_name)

            cp(src, dst, force = true)   # copy; force=true overwrites if exists
        end
    end
end

# Check the result
println("Files in $(output_dir):")
for f in sort(readdir(output_dir))
    println("  ", f)
end


#-----chunk 33------
# Source: chapters/02-files-data.qmd

# Clean up the fake directories
rm("fake_survey", recursive = true)
rm("collected_data", recursive = true)


#-----chunk 34------
# Source: chapters/02-files-data.qmd

using NCDatasets

# Read a NetCDF file
ds = NCDataset("temperature.nc")
temp = ds["temperature"][:, :, :]    # read the full 3D array
lat  = ds["latitude"][:]
lon  = ds["longitude"][:]
close(ds)

# Or use the do-block pattern (auto-closes)
NCDataset("temperature.nc") do ds
    temp = ds["temperature"][:, :, :]
    println("Shape: ", size(temp))
end


#-----chunk 35------
# Source: chapters/02-files-data.qmd

# Write a NetCDF file
NCDataset("output.nc", "c") do ds
    defDim(ds, "x", 10)
    defDim(ds, "y", 20)
    v = defVar(ds, "elevation", Float64, ("x", "y"))
    v[:, :] = rand(10, 20)
end


#-----chunk 36------
# Source: chapters/02-files-data.qmd

using HDF5

# Write
h5open("model.h5", "w") do f
    f["resistivity"] = rand(100, 100, 50)
    f["depth"] = collect(0.0:0.5:24.5)
end

# Read
h5open("model.h5", "r") do f
    rho   = read(f, "resistivity")
    depth = read(f, "depth")
    println("Model size: ", size(rho))
end


#-----chunk 37------
# Source: chapters/02-files-data.qmd

using SegyIO

# Read a SEG-Y file
block = segy_read("seismic_line.segy")
traces = block.data           # matrix of traces
headers = block.traceheaders   # trace header information


#-----chunk 38------
# Source: chapters/02-files-data.qmd

using Shapefile

table = Shapefile.Table("geology_map.shp")
# Access as a DataFrame
using DataFrames
df = DataFrame(table)


#-----chunk 39------
# Source: chapters/02-files-data.qmd

for f in ["stations.txt", "gravity.txt", "gravity_corrected.txt", "samples.csv"]
    isfile(f) && rm(f)
end
println("Cleaned up.")
