# Generated from chapters/04d-cnn.qmd
# Generated by scripts/00-extract_chapter_code.jl on 2026-05-15 02:38:51
# Regenerate with: julia scripts/00-extract_chapter_code.jl

#-----chunk 1------
# Source: chapters/04d-cnn.qmd

using Lux, Random, Optimisers, Zygote, Statistics, Printf, CairoMakie

rng = Xoshiro(42)
n = 64
class_names = ["Quiet", "Positive arrival", "Negative arrival"]


#-----chunk 2------
# Source: chapters/04d-cnn.qmd

# Generate one labelled synthetic seismic trace.
function make_trace_example(rng, n = n; class_id = rand(rng, 1:3))
    samples = Float32.(1:n)
    t = Float32.(range(0, 1, length = n))

    phase = rand(rng, Float32)
    trace = 0.03f0 .* randn(rng, Float32, n)
    trace .+= 0.04f0 .* sin.(2f0 * Float32(pi) .* (2.5f0 .* t .+ phase))

    if class_id != 1
        center = rand(rng, 12:n-12)
        width = 2.6f0 + 0.8f0 * rand(rng, Float32)
        polarity = class_id == 2 ? 1f0 : -1f0
        d = (samples .- center) ./ width
        wavelet = exp.(-0.5f0 .* d .^ 2)
        trace .+= polarity .* (0.90f0 + 0.10f0 * rand(rng, Float32)) .* wavelet
    end

    trace .-= mean(trace)
    trace = clamp.(trace, -1f0, 1f0)

    y = zeros(Float32, 3)
    y[class_id] = 1f0
    return reshape(trace, n, 1), y, class_id
end

n_samples = 180
X = zeros(Float32, n, 1, n_samples)    # (samples, channels, batch)
Y = zeros(Float32, 3, n_samples)
for i in 1:n_samples
    trace, y, _ = make_trace_example(rng; class_id = mod1(i, 3))
    X[:, :, i] = trace
    Y[:, i] = y
end

idx     = randperm(rng, n_samples)
n_train = round(Int, 0.80 * n_samples)
tr      = idx[1:n_train]
te      = idx[n_train+1:end]

X_train, Y_train = X[:, :, tr], Y[:, tr]
X_test,  Y_test  = X[:, :, te], Y[:, te]


#-----chunk 3------
# Source: chapters/04d-cnn.qmd

# Small 1D CNN classifier.
model = Chain(
    Conv((5,), 1 => 8, relu; pad = SamePad()),
    MaxPool((2,)),                                # 32 samples
    WrappedFunction(x -> reshape(x, :, size(x, 3))),
    Dense(8 * 32 => 16, relu),
    Dense(16 => 3),
)

ps, st = Lux.setup(rng, model)

function softmax_cols(x)
    x_shift = x .- maximum(x, dims = 1)
    ex = exp.(x_shift)
    ex ./ sum(ex, dims = 1)
end

function cross_entropy_loss(model, ps, st, data)
    x, y = data
    logits, st_new = model(x, ps, st)
    prob = softmax_cols(logits)
    loss = -mean(sum(y .* log.(prob .+ 1f-7), dims = 1))
    return loss, st_new, ()
end

function predicted_classes(probabilities)
    [findmax(probabilities[:, i])[2] for i in axes(probabilities, 2)]
end

function true_classes(labels)
    [findmax(labels[:, i])[2] for i in axes(labels, 2)]
end


#-----chunk 4------
# Source: chapters/04d-cnn.qmd

function train_classifier(model, ps, st, data; epochs = 60, lr = 5f-3)
    tstate = Training.TrainState(model, ps, st, Adam(lr))
    for epoch in 1:epochs
        _, loss, _, tstate = Training.single_train_step!(
            AutoZygote(), cross_entropy_loss, data, tstate
        )
        if epoch == 1 || epoch % 15 == 0
            @printf "Epoch %2d  cross-entropy = %.4f\n" epoch loss
        end
    end
    return tstate
end

tstate = train_classifier(model, ps, st, (X_train, Y_train))


#-----chunk 5------
# Source: chapters/04d-cnn.qmd

test_logits, _ = model(X_test, tstate.parameters, tstate.states)
test_prob = softmax_cols(test_logits)
test_loss = -mean(sum(Y_test .* log.(test_prob .+ 1f-7), dims = 1))
test_acc = mean(predicted_classes(test_prob) .== true_classes(Y_test))
@printf "Holdout cross-entropy: %.4f  Accuracy: %.3f\n" test_loss test_acc

for i in 1:3
    class_idx = true_classes(Y_test) .== i
    class_acc = mean(predicted_classes(test_prob)[class_idx] .== i)
    @printf "%s accuracy: %.3f\n" class_names[i] class_acc
end


#-----chunk 6------
# Source: chapters/04d-cnn.qmd

function sample_with_label(seed, wanted_label)
    rng_local = Xoshiro(seed)
    while true
        x, y, class_id = make_trace_example(rng_local)
        class_id == wanted_label && return x, y, class_id
    end
end

examples = [sample_with_label(100 + 17i, i) for i in 1:3]
fig = Figure(size = (720, 620))

for (row, (trace, _, class_id)) in enumerate(examples)
    logits, _ = model(reshape(trace, n, 1, 1), tstate.parameters, tstate.states)
    prob = softmax_cols(logits)
    predicted = findmax(prob[:, 1])[2]

    ax = Axis(fig[row, 1],
              title = "$(class_names[class_id]) -> $(class_names[predicted])",
              xlabel = row == 3 ? "sample" : "",
              ylabel = "amplitude")
    lines!(ax, 1:n, trace[:, 1]; color = :black, linewidth = 1.6)
    ylims!(ax, -1.05, 1.05)
end
fig
