# Generated from chapters/04i-gan.qmd
# Generated by scripts/extract_chapter_code.jl on 2026-04-04 00:23:54
# Regenerate with: julia scripts/extract_chapter_code.jl

#-----chunk 1------
# Source: chapters/04i-gan.qmd

using Lux, Random, Optimisers, Zygote, Statistics, Printf, CairoMakie

rng = Xoshiro(42)

# Generate synthetic porosity-velocity pairs for two rock populations.
function make_crossplot_sample(rng)
    if rand(rng) < 0.5f0
        # High-porosity, lower-velocity population
        ϕ = clamp(0.28f0 + 0.025f0 * randn(rng, Float32), 0.18f0, 0.36f0)
        vₚ = 3.15f0 - 1.35f0 * (ϕ - 0.28f0) + 0.05f0 * randn(rng, Float32)
    else
        # Tight, lower-porosity, higher-velocity population
        ϕ = clamp(0.085f0 + 0.015f0 * randn(rng, Float32), 0.03f0, 0.14f0)
        vₚ = 4.55f0 - 0.85f0 * (ϕ - 0.085f0) + 0.04f0 * randn(rng, Float32)
    end
    return Float32[ϕ, vₚ]
end

n_real = 512
real_data = zeros(Float32, 2, n_real)
for i in 1:n_real
    real_data[:, i] = make_crossplot_sample(rng)
end

μ_cross = mean(real_data, dims = 2)
σ_cross = std(real_data, dims = 2)
real_data_scaled = (real_data .- μ_cross) ./ σ_cross


#-----chunk 2------
# Source: chapters/04i-gan.qmd

# Generator: noise → synthetic porosity-velocity pair
latent_dim = 4
generator = Chain(
    Dense(latent_dim => 48, relu),
    Dense(48 => 48, relu),
    Dense(48 => 2)
)

# Critic: porosity-velocity pair → realism score
critic = Chain(
    Dense(2 => 48, leakyrelu),
    Dense(48 => 48, leakyrelu),
    Dense(48 => 1)
)

ps_g, st_g = Lux.setup(rng, generator)
ps_c, st_c = Lux.setup(rng, critic)


#-----chunk 3------
# Source: chapters/04i-gan.qmd

function sample_batch(rng, data, batch_size)
    idx = rand(rng, 1:size(data, 2), batch_size)
    data[:, idx]
end

function clip_params(x, clip_value)
    if x isa NamedTuple
        names = fieldnames(typeof(x))
        values = map(name -> clip_params(getfield(x, name), clip_value), names)
        return NamedTuple{names}(Tuple(values))
    elseif x isa AbstractArray
        return clamp.(x, -clip_value, clip_value)
    else
        return x
    end
end

function train_wgan(generator, critic, ps_g, st_g, ps_c, st_c;
                    epochs = 700, batch_size = 128, critic_steps = 4,
                    lr_g = 0.00025f0, lr_c = 0.00025f0, clip_value = 0.03f0)
    opt_state_g = Optimisers.setup(RMSProp(lr_g), ps_g)
    opt_state_c = Optimisers.setup(RMSProp(lr_c), ps_c)

    for epoch in 1:epochs
        critic_loss = 0.0f0
        for _ in 1:critic_steps
            x_real = sample_batch(rng, real_data_scaled, batch_size)
            z = randn(rng, Float32, latent_dim, batch_size)

            (c_loss, st_c_new), c_grads = Zygote.withgradient(ps_c) do pc
                fake, _ = generator(z, ps_g, st_g)
                real_score, st_c1 = critic(x_real, pc, st_c)
                fake_score, st_c2 = critic(fake, pc, st_c1)
                loss = mean(fake_score) - mean(real_score)
                return loss, st_c2
            end

            opt_state_c, ps_c = Optimisers.update(opt_state_c, ps_c, c_grads[1])
            ps_c = clip_params(ps_c, clip_value)
            st_c = st_c_new
            critic_loss = c_loss
        end

        z = randn(rng, Float32, latent_dim, batch_size)
        (g_loss, st_g_new), g_grads = Zygote.withgradient(ps_g) do pg
            fake, st_g_ = generator(z, pg, st_g)
            fake_score, _ = critic(fake, ps_c, st_c)
            loss = -mean(fake_score)
            return loss, st_g_
        end

        opt_state_g, ps_g = Optimisers.update(opt_state_g, ps_g, g_grads[1])
        st_g = st_g_new

        if epoch == 1 || epoch % 140 == 0
            @printf "Epoch %3d  critic loss: %.4f  generator loss: %.4f\n" epoch critic_loss g_loss
        end
    end

    return ps_g, st_g, ps_c, st_c
end

ps_g, st_g, ps_c, st_c = train_wgan(generator, critic, ps_g, st_g, ps_c, st_c)


#-----chunk 4------
# Source: chapters/04i-gan.qmd

# Generate synthetic crossplot samples
z_test = randn(rng, Float32, latent_dim, n_real)
fake_points, _ = generator(z_test, ps_g, st_g)
fake_points = fake_points .* σ_cross .+ μ_cross

# Simple distribution checks (not sufficient alone, but useful sanity checks)
@printf "Real porosity mean/std: %.3f / %.3f\n" mean(real_data[1, :]) std(real_data[1, :])
@printf "Fake porosity mean/std: %.3f / %.3f\n" mean(fake_points[1, :]) std(fake_points[1, :])
@printf "Real velocity mean/std: %.3f / %.3f\n" mean(real_data[2, :]) std(real_data[2, :])
@printf "Fake velocity mean/std: %.3f / %.3f\n" mean(fake_points[2, :]) std(fake_points[2, :])

fig = Figure(size = (620, 330))
ax1 = Axis(fig[1, 1], title = "Real crossplot",
           xlabel = "Porosity", ylabel = "P-wave velocity (km/s)")
scatter!(ax1, real_data[1, :], real_data[2, :], color = (:black, 0.45), markersize = 7)

ax2 = Axis(fig[1, 2], title = "GAN-generated crossplot",
           xlabel = "Porosity", ylabel = "P-wave velocity (km/s)")
scatter!(ax2, fake_points[1, :], fake_points[2, :], color = (:coral, 0.45), markersize = 7)

Label(fig[0, :], "GAN: Real vs Generated Rock-Physics Crossplots",
      fontsize = 16)
fig
