# Generated from chapters/05-inverse-modeling.qmd
# Generated by scripts/extract_chapter_code.jl on 2026-04-04 00:23:54
# Regenerate with: julia scripts/extract_chapter_code.jl

# No Julia code blocks were found in this chapter.
