# Generated from chapters/05a-pinn.qmd
# Generated by scripts/extract_chapter_code.jl on 2026-04-04 00:23:54
# Regenerate with: julia scripts/extract_chapter_code.jl

#-----chunk 1------
# Source: chapters/05a-pinn.qmd

using Lux, Random, Optimisers, Zygote, Statistics, Printf, CairoMakie

rng = Xoshiro(42)
α = 0.01f0   # thermal diffusivity

# Exact solution for comparison
u_exact(x, t) = exp(-α * π^2 * t) * sin(π * x)


#-----chunk 2------
# Source: chapters/05a-pinn.qmd

# Sample collocation points (interior), boundary points, and initial points
n_interior = 1000
n_bc = 200
n_ic = 200

# Interior points: random (x, t) in (0,1) × (0,1)
x_int = rand(rng, Float32, 1, n_interior)
t_int = rand(rng, Float32, 1, n_interior)

# Boundary: x = 0 and x = 1
t_bc = rand(rng, Float32, 1, n_bc)
x_bc_0 = zeros(Float32, 1, n_bc)
x_bc_1 = ones(Float32, 1, n_bc)

# Initial condition: t = 0
x_ic = rand(rng, Float32, 1, n_ic)
u_ic = sin.(π .* x_ic)


#-----chunk 3------
# Source: chapters/05a-pinn.qmd

# Build the PINN: input (x, t) → output u
model = Chain(
    Dense(2 => 32, tanh),
    Dense(32 => 32, tanh),
    Dense(32 => 32, tanh),
    Dense(32 => 1)
)

ps, st = Lux.setup(rng, model)


#-----chunk 4------
# Source: chapters/05a-pinn.qmd

#-----PINN loss------
function pinn_loss(model, ps, st, data)
    x_i, t_i, x_b0, x_b1, t_b, x_ic_, u_ic_ = data
    λᵣ = 1.0f0
    λᵦ = 10.0f0
    λ₀ = 10.0f0
    
    #-----PDE residual------
    function u_pred(xt)
        input = reshape(xt, 2, 1)
        out, _ = model(input, ps, st)
        return out[1]
    end

    residuals = zeros(Float32, n_interior)
    for i in 1:n_interior
        xt = Float32[x_i[i], t_i[i]]
        grad1 = Zygote.gradient(x -> u_pred(x), xt)[1]
        du_dt = grad1[2]
        d2u_dx2 = Zygote.gradient(x -> Zygote.gradient(y -> u_pred(y), x)[1][1], xt)[1][1]
        residuals[i] = du_dt - α * d2u_dx2
    end

    residual = reshape(residuals, 1, :)
    loss_pde = mean(residual .^ 2)
    
    #-----boundary loss------
    bc_input_0 = vcat(x_b0, t_b)
    bc_input_1 = vcat(x_b1, t_b)
    u_b0, _ = model(bc_input_0, ps, st)
    u_b1, _ = model(bc_input_1, ps, st)
    loss_bc = mean(u_b0 .^ 2) + mean(u_b1 .^ 2)
    
    #-----initial-condition loss------
    ic_input = vcat(x_ic_, zeros(Float32, 1, size(x_ic_, 2)))
    u_0, _ = model(ic_input, ps, st)
    loss_ic = mean((u_0 .- u_ic_) .^ 2)
    
    total = λᵣ * loss_pde + λᵦ * loss_bc + λ₀ * loss_ic
    return total, st, ()
end


#-----chunk 5------
# Source: chapters/05a-pinn.qmd

# Train the PINN
opt = Adam(0.001f0)
tstate = Training.TrainState(model, ps, st, opt)

data = (x_int, t_int, x_bc_0, x_bc_1, t_bc, x_ic, u_ic)

for epoch in 1:500
    _, loss, _, tstate = Training.single_train_step!(
        AutoZygote(), pinn_loss, data, tstate
    )
    if epoch == 1 || epoch % 100 == 0
        @printf "Epoch %4d  Loss = %.6f\n" epoch loss
    end
end


#-----chunk 6------
# Source: chapters/05a-pinn.qmd

# Compare PINN solution to exact solution
nx, nt = 50, 50
xs = Float32.(range(0, 1, length = nx))
ts = Float32.(range(0, 1, length = nt))

U_pinn = zeros(Float32, nx, nt)
U_true = zeros(Float32, nx, nt)

for (j, tj) in enumerate(ts)
    input = vcat(reshape(xs, 1, :), fill(tj, 1, nx))
    pred, _ = model(input, tstate.parameters, tstate.states)
    U_pinn[:, j] = vec(pred)
    U_true[:, j] = u_exact.(xs, tj)
end

fig = Figure(size = (700, 300))
ax1 = Axis(fig[1, 1], title = "PINN solution", xlabel = "x", ylabel = "t")
heatmap!(ax1, xs, ts, U_pinn, colormap = :viridis)
ax2 = Axis(fig[1, 2], title = "Exact solution", xlabel = "x", ylabel = "t")
heatmap!(ax2, xs, ts, U_true, colormap = :viridis)
ax3 = Axis(fig[1, 3], title = "Absolute error", xlabel = "x", ylabel = "t")
heatmap!(ax3, xs, ts, abs.(U_pinn .- U_true), colormap = :hot)
fig
