# Generated from chapters/05b-physics-ml-inversion.qmd
# Generated by scripts/extract_chapter_code.jl on 2026-04-04 00:23:54
# Regenerate with: julia scripts/extract_chapter_code.jl

#-----chunk 1------
# Source: chapters/05b-physics-ml-inversion.qmd

using Lux, Random, Optimisers, Zygote, Statistics, Printf, CairoMakie

rng = Xoshiro(42)


#-----chunk 2------
# Source: chapters/05b-physics-ml-inversion.qmd

# True diffusion coefficient (what we want to recover)
κ_true(x) = 1.0f0 + 0.5f0 * sin(2π * x)

# Source term
f_source(x) = sin(2π * x)

# Generate "observed" data by solving the ODE numerically (finite differences)
nx_fd = 200
x_fd = Float32.(range(0, 1, length = nx_fd))
dx_fd = x_fd[2] - x_fd[1]

# Build FD system: -d/dx[κ du/dx] = f
# Using central differences
A = zeros(Float32, nx_fd, nx_fd)
rhs = zeros(Float32, nx_fd)

A[1, 1] = 1.0f0   # u(0) = 0
A[end, end] = 1.0f0  # u(1) = 0

for i in 2:nx_fd-1
    κ_plus  = 0.5f0 * (κ_true(x_fd[i]) + κ_true(x_fd[i+1]))
    κ_minus = 0.5f0 * (κ_true(x_fd[i]) + κ_true(x_fd[i-1]))
    A[i, i-1] = -κ_minus / dx_fd^2
    A[i, i]   = (κ_plus + κ_minus) / dx_fd^2
    A[i, i+1] = -κ_plus / dx_fd^2
    rhs[i] = f_source(x_fd[i])
end

u_fd = A \ rhs

# Sample noisy observations at sparse locations
n_obs = 20
obs_idx = sort(rand(rng, 2:nx_fd-1, n_obs))
x_obs = x_fd[obs_idx]
u_obs = u_fd[obs_idx] .+ 0.005f0 .* randn(rng, Float32, n_obs)


#-----chunk 3------
# Source: chapters/05b-physics-ml-inversion.qmd

# Plot the true solution and observations
fig = Figure(size = (700, 250))
ax1 = Axis(fig[1, 1], xlabel = "x", ylabel = "u(x)", title = "Solution field")
lines!(ax1, x_fd, u_fd, color = :black, linewidth = 2, label = "True u(x)")
scatter!(ax1, x_obs, u_obs, color = :red, markersize = 8, label = "Observations")
axislegend(ax1, position = :rt)

ax2 = Axis(fig[1, 2], xlabel = "x", ylabel = "κ(x)", title = "Diffusion coefficient")
lines!(ax2, x_fd, κ_true.(x_fd), color = :black, linewidth = 2, label = "True κ(x)")
axislegend(ax2, position = :rb)
fig


#-----chunk 4------
# Source: chapters/05b-physics-ml-inversion.qmd

#-----κ representation------
n_features = 32
B_matrix = randn(rng, Float32, n_features, 1) .* 4.0f0  # frequency scale

function fourier_encode(x, B)
    projected = B * reshape(x, 1, :)  # (n_features, n_points)
    return vcat(sin.(2π .* projected), cos.(2π .* projected))  # (2*n_features, n_points)
end

#-----κ-network------
κ_model = Chain(
    Dense(2 * n_features => 64, tanh),
    Dense(64 => 64, tanh),
    Dense(64 => 1)
)

#-----u-network------
u_model = Chain(
    Dense(2 * n_features => 64, tanh),
    Dense(64 => 64, tanh),
    Dense(64 => 1)
)

ps_κ, st_κ = Lux.setup(rng, κ_model)
ps_u, st_u = Lux.setup(rng, u_model)


#-----chunk 5------
# Source: chapters/05b-physics-ml-inversion.qmd

#-----combined loss------
function inversion_loss(ps_κ, ps_u, st_κ, st_u)
    λᵣ = 1.0f0
    λᵦ = 10.0f0

    # Evaluate κ and u at collocation points
    n_colloc = 100
    x_c = Float32.(range(0.01, 0.99, length = n_colloc))
    x_c_enc = fourier_encode(x_c, B_matrix)
    
    # Predict κ at collocation points (enforce positivity with softplus)
    κ_pred_raw, _ = κ_model(x_c_enc, ps_κ, st_κ)
    κ_pred = Lux.NNlib.softplus.(κ_pred_raw)  # ensure κ > 0
    
    # Predict u at collocation points
    u_pred_c, _ = u_model(x_c_enc, ps_u, st_u)
    
    # PDE residual via AD: -d/dx[κ du/dx] - f = 0
    # We compute du/dx and d(κ du/dx)/dx using finite differences on the
    # collocation grid (dense enough for accuracy), keeping AD for the networks
    δx = x_c[2] - x_c[1]
    u_vec = vec(u_pred_c)
    κ_vec = vec(κ_pred)
    
    # du/dx at half-points
    du_dx = diff(u_vec) ./ δx  # (n_colloc - 1,)
    # κ at half-points
    κ_half = 0.5f0 .* (κ_vec[1:end-1] .+ κ_vec[2:end])
    # flux: κ * du/dx
    flux = κ_half .* du_dx
    # d(flux)/dx at interior points
    d_flux_dx = diff(flux) ./ δx  # (n_colloc - 2,)
    
    f_vals = f_source.(x_c[2:end-1])
    pde_residual = -d_flux_dx .- f_vals
    loss_pde = mean(pde_residual .^ 2)
    
    # Data misfit: compare u predictions at observation locations
    x_obs_enc = fourier_encode(x_obs, B_matrix)
    u_pred_obs, _ = u_model(x_obs_enc, ps_u, st_u)
    loss_data = mean((vec(u_pred_obs) .- u_obs) .^ 2)
    
    # Boundary conditions: u(0) = 0, u(1) = 0
    x_bc = Float32[0.0, 1.0]
    x_bc_enc = fourier_encode(x_bc, B_matrix)
    u_bc, _ = u_model(x_bc_enc, ps_u, st_u)
    loss_bc = mean(u_bc .^ 2)
    
    total = loss_data + λᵣ * loss_pde + λᵦ * loss_bc
    return total
end


#-----chunk 6------
# Source: chapters/05b-physics-ml-inversion.qmd

# Train both networks jointly
opt_κ = Adam(0.001f0)
opt_u = Adam(0.001f0)
opt_state_κ = Optimisers.setup(opt_κ, ps_κ)
opt_state_u = Optimisers.setup(opt_u, ps_u)

for epoch in 1:2000
    (loss_val), grads = Zygote.withgradient(ps_κ, ps_u) do pκ, pu
        inversion_loss(pκ, pu, st_κ, st_u)
    end
    
    opt_state_κ, ps_κ = Optimisers.update(opt_state_κ, ps_κ, grads[1])
    opt_state_u, ps_u = Optimisers.update(opt_state_u, ps_u, grads[2])
    
    if epoch == 1 || epoch % 400 == 0
        @printf "Epoch %4d  Loss = %.6f\n" epoch loss_val
    end
end


#-----chunk 7------
# Source: chapters/05b-physics-ml-inversion.qmd

# Compare recovered κ to the true one
x_plot = Float32.(range(0, 1, length = 200))
x_plot_enc = fourier_encode(x_plot, B_matrix)

κ_recovered_raw, _ = κ_model(x_plot_enc, ps_κ, st_κ)
κ_recovered = vec(Lux.NNlib.softplus.(κ_recovered_raw))

u_recovered, _ = u_model(x_plot_enc, ps_u, st_u)
u_recovered = vec(u_recovered)

fig = Figure(size = (700, 300))
ax1 = Axis(fig[1, 1], xlabel = "x", ylabel = "κ(x)",
           title = "Recovered diffusion coefficient")
lines!(ax1, x_plot, κ_true.(x_plot), color = :black, linewidth = 2,
       label = "True κ(x)")
lines!(ax1, x_plot, κ_recovered, color = :steelblue, linewidth = 2,
       linestyle = :dash, label = "INR recovered")
axislegend(ax1, position = :rb)

ax2 = Axis(fig[1, 2], xlabel = "x", ylabel = "u(x)",
           title = "Recovered solution field")
lines!(ax2, x_fd, u_fd, color = :black, linewidth = 2, label = "True u(x)")
lines!(ax2, x_plot, u_recovered, color = :steelblue, linewidth = 2,
       linestyle = :dash, label = "INR recovered")
scatter!(ax2, x_obs, u_obs, color = :red, markersize = 6, label = "Observations")
axislegend(ax2, position = :rt)
fig
