# Generated from chapters/05e-fno.qmd
# Generated by scripts/extract_chapter_code.jl on 2026-04-04 00:23:54
# Regenerate with: julia scripts/extract_chapter_code.jl

#-----chunk 1------
# Source: chapters/05e-fno.qmd

using Lux, Random, Optimisers, Zygote, Statistics, Printf, CairoMakie, FFTW

rng = Xoshiro(42)


#-----chunk 2------
# Source: chapters/05e-fno.qmd

# Generate training data: advection with periodic BCs
nx = 64
c = 1.0f0
T_final = 0.5f0
dx = 1.0f0 / nx
x_grid = Float32.(range(0, 1 - dx, length = nx))

function generate_pair(rng)
    # Random initial condition: sum of sinusoids
    n_modes = rand(rng, 2:5)
    u0 = zeros(Float32, nx)
    for _ in 1:n_modes
        k = rand(rng, 1:6)
        a = 0.5f0 * randn(rng, Float32)
        ϕ = 2π * rand(rng, Float32)
        u0 .+= a .* sin.(2π .* k .* x_grid .+ ϕ)
    end
    # Exact solution at t = T: shift by c*T (periodic)
    shift = round(Int, c * T_final / dx)
    uT = circshift(u0, -shift)
    return u0, uT
end

n_train = 500
n_test = 100
U0_train = zeros(Float32, nx, n_train)
UT_train = zeros(Float32, nx, n_train)

for i in 1:n_train
    u0, uT = generate_pair(rng)
    U0_train[:, i] = u0
    UT_train[:, i] = uT
end

U0_test = zeros(Float32, nx, n_test)
UT_test = zeros(Float32, nx, n_test)
for i in 1:n_test
    u0, uT = generate_pair(Xoshiro(9000 + i))
    U0_test[:, i] = u0
    UT_test[:, i] = uT
end


#-----chunk 3------
# Source: chapters/05e-fno.qmd

# Spectral convolution layer (custom Lux layer)
struct SpectralConv <: Lux.AbstractLuxLayer
    in_channels::Int
    out_channels::Int
    modes::Int
end

function Lux.initialparameters(rng::AbstractRNG, l::SpectralConv)
    scale = 1.0f0 / (l.in_channels * l.out_channels)
    R_real = scale .* randn(rng, Float32, l.out_channels, l.in_channels, l.modes)
    R_imag = scale .* randn(rng, Float32, l.out_channels, l.in_channels, l.modes)
    return (R_real = R_real, R_imag = R_imag)
end

Lux.initialstates(::AbstractRNG, ::SpectralConv) = NamedTuple()

function (l::SpectralConv)(x, ps, st)
    # x: (nx, channels, batch)
    nx_in = size(x, 1)
    batch = size(x, 3)
    
    # FFT along spatial dimension
    x_ft = rfft(x, 1)  # (nx÷2+1, channels, batch)
    
    # Multiply by learned weights for first `modes` frequencies
    R = complex.(ps.R_real, ps.R_imag)  # (out_ch, in_ch, modes)
    
    out_ft = zeros(ComplexF32, size(x_ft, 1), l.out_channels, batch)
    for b in 1:batch
        for k in 1:l.modes
            for o in 1:l.out_channels
                for ic in 1:l.in_channels
                    out_ft[k, o, b] += R[o, ic, k] * x_ft[k, ic, b]
                end
            end
        end
    end
    
    # Inverse FFT
    out = irfft(out_ft, nx_in, 1)
    return out, st
end


#-----chunk 4------
# Source: chapters/05e-fno.qmd

# Build FNO: lift → spectral layers → project
modes = 12
width = 16

lift = Dense(1 => width)

spectral1 = SpectralConv(width, width, modes)
skip1 = Dense(width => width)

spectral2 = SpectralConv(width, width, modes)
skip2 = Dense(width => width)

spectral3 = SpectralConv(width, width, modes)
skip3 = Dense(width => width)

project = Dense(width => 1)

ps_lift, st_lift = Lux.setup(rng, lift)
ps_s1, st_s1 = Lux.setup(rng, spectral1)
ps_sk1, st_sk1 = Lux.setup(rng, skip1)
ps_s2, st_s2 = Lux.setup(rng, spectral2)
ps_sk2, st_sk2 = Lux.setup(rng, skip2)
ps_s3, st_s3 = Lux.setup(rng, spectral3)
ps_sk3, st_sk3 = Lux.setup(rng, skip3)
ps_proj, st_proj = Lux.setup(rng, project)

ps_all = (lift = ps_lift,
          s1 = ps_s1, sk1 = ps_sk1,
          s2 = ps_s2, sk2 = ps_sk2,
          s3 = ps_s3, sk3 = ps_sk3,
          proj = ps_proj)
st_all = (lift = st_lift,
          s1 = st_s1, sk1 = st_sk1,
          s2 = st_s2, sk2 = st_sk2,
          s3 = st_s3, sk3 = st_sk3,
          proj = st_proj)

function fno_forward(x, ps, st)
    # x: (nx, 1, batch)
    nx_in, _, batch = size(x)
    
    # Lift to higher dimension
    x_flat = reshape(x, 1, nx_in * batch)
    v, st_l = lift(x_flat, ps.lift, st.lift)
    v = reshape(v, nx_in, width, batch)
    
    # Fourier layer 1
    v_spec, st_s1 = spectral1(v, ps.s1, st.s1)
    v_skip = reshape(v, width, nx_in * batch)
    v_local, st_sk1 = skip1(v_skip, ps.sk1, st.sk1)
    v_local = reshape(v_local, nx_in, width, batch)
    v = relu.(v_spec .+ v_local)
    
    # Fourier layer 2
    v_spec2, st_s2 = spectral2(v, ps.s2, st.s2)
    v_skip2 = reshape(v, width, nx_in * batch)
    v_local2, st_sk2 = skip2(v_skip2, ps.sk2, st.sk2)
    v_local2 = reshape(v_local2, nx_in, width, batch)
    v = relu.(v_spec2 .+ v_local2)
    
    # Fourier layer 3
    v_spec3, st_s3 = spectral3(v, ps.s3, st.s3)
    v_skip3 = reshape(v, width, nx_in * batch)
    v_local3, st_sk3 = skip3(v_skip3, ps.sk3, st.sk3)
    v_local3 = reshape(v_local3, nx_in, width, batch)
    v = relu.(v_spec3 .+ v_local3)
    
    # Project back
    v_flat = reshape(v, width, nx_in * batch)
    out, st_p = project(v_flat, ps.proj, st.proj)
    out = reshape(out, nx_in, 1, batch)
    
    st_new = (lift = st_l,
              s1 = st_s1, sk1 = st_sk1,
              s2 = st_s2, sk2 = st_sk2,
              s3 = st_s3, sk3 = st_sk3,
              proj = st_p)
    return out, st_new
end


#-----chunk 5------
# Source: chapters/05e-fno.qmd

# Training loop
opt = Adam(0.001f0)
opt_state = Optimisers.setup(opt, ps_all)

X_train = reshape(U0_train, nx, 1, n_train)
Y_train = reshape(UT_train, nx, 1, n_train)
X_test = reshape(U0_test, nx, 1, n_test)
Y_test = reshape(UT_test, nx, 1, n_test)

for epoch in 1:500
    (loss, st_new), grads = Zygote.withgradient(ps_all) do ps
        pred, st_ = fno_forward(X_train, ps, st_all)
        l = mean((pred .- Y_train) .^ 2)
        (l, st_)
    end
    opt_state, ps_all = Optimisers.update(opt_state, ps_all, grads[1])
    st_all = st_new
    
    if epoch == 1 || epoch % 100 == 0
        pred_test, _ = fno_forward(X_test, ps_all, st_all)
        test_mse = mean((pred_test .- Y_test) .^ 2)
        @printf "Epoch %3d  Train MSE = %.6f  Test MSE = %.6f\n" epoch loss test_mse
    end
end


#-----chunk 6------
# Source: chapters/05e-fno.qmd

# Test on new initial conditions
n_show = 4
fig = Figure(size = (700, 500))

for i in 1:n_show
    u0_test, uT_test = generate_pair(Xoshiro(5000 + i))
    x_in = reshape(u0_test, nx, 1, 1)
    pred, _ = fno_forward(x_in, ps_all, st_all)
    
    row = (i - 1) ÷ 2 + 1
    col = (i - 1) % 2 + 1
    ax = Axis(fig[row, col], title = "Test $i",
              xlabel = "x", ylabel = "u")
    lines!(ax, x_grid, u0_test, color = (:gray, 0.5), label = "u₀")
    lines!(ax, x_grid, uT_test, color = :black, linewidth = 2, label = "Exact u(T)")
    lines!(ax, x_grid, vec(pred), color = :steelblue, linewidth = 2,
           linestyle = :dash, label = "FNO prediction")
    if i == 1
        axislegend(ax, position = :rt, labelsize = 10)
    end
end

Label(fig[0, :], "FNO: advection equation — generalizing to new initial conditions",
      fontsize = 14)
fig
